version: '2.0'
services:

  node:
    image: parity/parity:v2.3.3
    restart: always
    command:
      --config /parity/config/authority.toml
      --nat extip:${EXTERNAL_IP}
    volumes:
      - ./config:/parity/config:ro
      - ./chain:/home/parity/.local/share/io.parity.ethereum/
      - ./.secret:/parity/authority.pwd:ro
    ports:
      - 30303:30303 
      - 30303:30303/udp

  netstats:
    image: buythewhale/ethstats_monitor
    restart: always
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
